# Generated by Django 3.1.3 on 2021-05-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20210508_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='discount',
            field=models.FloatField(blank=True, default=0, help_text='Accpted inputs are (0 to 1', null=True, verbose_name='Discount'),
        ),
    ]
