# Generated by Django 3.1.3 on 2021-06-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20210509_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['price']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-last_modified']},
        ),
    ]
