# Generated by Django 3.1.3 on 2021-02-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(help_text='Select is student user', null=True, verbose_name='Student?'),
        ),
    ]
