# Generated by Django 3.1.3 on 2021-02-01 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harrp', '0002_auto_20210201_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Phone'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(choices=[('Abia', 'Abia'), ('Abuja', ' Abuja'), ('Adamawa', ' Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', ' Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=255, verbose_name='State')),
                ('country', models.CharField(choices=[('Nigeria', 'Nigeria')], max_length=50, verbose_name='Country')),
                ('dob', models.DateField(verbose_name='Date Of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, verbose_name='Gender')),
                ('school', models.CharField(choices=[('Lekki Britsh School', 'Lekki Britsh School'), ('Penny International Colledge', 'Penny International Colledge'), ('Dowen Colledge', 'Dowen Colledge'), ('Children International School', 'Children International School')], max_length=255, verbose_name='School')),
                ('level', models.CharField(choices=[('Junior Secondary, School', 'Junior Secondary, School'), ('Senior Secondary, School', 'Senior Secondary, School')], max_length=50, verbose_name='Level')),
                ('id_number', models.CharField(help_text='Matric no / Exam No/ Registration No', max_length=50, verbose_name='Identification')),
                ('guard_one_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('guard_two_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('guard_one_phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('guard_two_phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
