# Generated by Django 3.1.3 on 2021-02-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrp', '0003_auto_20210201_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='guard_one_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guard_two_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id_number',
            field=models.CharField(blank=True, help_text='Matric no / Exam No/ Registration No', max_length=50, null=True, verbose_name='Identification'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.CharField(blank=True, choices=[('Lekki Britsh School', 'Lekki Britsh School'), ('Penny International Colledge', 'Penny International Colledge'), ('Dowen Colledge', 'Dowen Colledge'), ('Children International School', 'Children International School')], max_length=255, null=True, verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, help_text='Select is student user', null=True, verbose_name='Student?'),
        ),
    ]
