# Generated by Django 3.1.3 on 2021-02-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrp', '0004_auto_20210201_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False, help_text='Phone number verified?', verbose_name='Verified'),
        ),
    ]
