# Generated by Django 3.1.3 on 2021-02-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrp', '0005_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_count',
            field=models.IntegerField(default=0, verbose_name='Count'),
        ),
    ]
