# Generated by Django 3.1.3 on 2021-02-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrp', '0008_auto_20210219_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='students',
            field=models.ManyToManyField(to='harrp.StudentProfile', verbose_name='students'),
        ),
    ]
