# Generated by Django 3.1.3 on 2021-02-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrp', '0009_auto_20210220_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='students',
            field=models.ManyToManyField(related_name='schools', to='harrp.StudentProfile', verbose_name='students'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(choices=[('Junior Secondary', 'Junior Secondary'), ('Senior Secondary', 'Senior Secondary')], max_length=50, verbose_name='Level'),
        ),
    ]
