# Generated by Django 3.1.3 on 2021-04-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrp', '0011_auto_20210428_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='guard_one_phone',
            field=models.CharField(default='08162300796', max_length=15, verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guard_two_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
