# Generated by Django 3.1.3 on 2021-04-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrp', '0012_auto_20210428_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='students',
            field=models.ManyToManyField(related_name='schools', to='harrp.StudentProfile', verbose_name='students'),
        ),
    ]
