# Generated by Django 3.1.3 on 2021-05-03 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0006_auto_20210503_2025'),
        ('harrp', '0013_auto_20210428_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='others.level', verbose_name='Level'),
        ),
    ]
