# Generated by Django 3.1.3 on 2021-05-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrp', '0014_auto_20210503_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True, help_text='Select is student user', null=True, verbose_name='Student?'),
        ),
    ]
