# Generated by Django 3.1.3 on 2021-04-29 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0005_auto_20210428_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('qtn_type', models.CharField(choices=[('MTC', 'Multichoice'), ('SUB', 'Subjective')], default='MTC', max_length=255, verbose_name='Question Type')),
                ('opt_a', models.CharField(blank=True, max_length=255, null=True, verbose_name='Option A')),
                ('opt_b', models.CharField(blank=True, max_length=255, null=True, verbose_name='Option B')),
                ('opt_c', models.CharField(blank=True, max_length=255, null=True, verbose_name='Option C')),
                ('opt_d', models.CharField(blank=True, max_length=255, null=True, verbose_name='Option D')),
                ('opt_e', models.CharField(blank=True, max_length=255, null=True, verbose_name='Option E')),
                ('answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Answer')),
                ('hint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hint')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lesson', verbose_name='Lesson')),
            ],
        ),
    ]
