# Generated by Django 3.1.3 on 2021-04-29 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20210428_2029'),
        ('exercises', '0002_auto_20210429_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='score',
            field=models.IntegerField(default=5, help_text='How many point question carries', verbose_name='Score'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='lessons.lesson', verbose_name='Lesson'),
        ),
    ]
