# Generated by Django 3.1.3 on 2021-04-29 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_auto_20210428_1956'),
        ('exercises', '0004_auto_20210429_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='others.topic', verbose_name='Topic'),
        ),
    ]
