# Generated by Django 3.1.3 on 2021-02-20 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Junior Secondary', 'Junior Secondary'), ('Senior Secondary', 'Senior Secondary')], max_length=50, verbose_name='Title')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level', to='others.level', verbose_name='Level'),
        ),
    ]
