# Generated by Django 3.1.3 on 2021-04-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_auto_20210220_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level', to='others.level', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='Icon'),
        ),
    ]
