# Generated by Django 3.1.3 on 2021-04-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_auto_20210428_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.ManyToManyField(related_name='level', to='others.Level', verbose_name='Level'),
        ),
    ]
