# Generated by Django 3.1.3 on 2021-02-20 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harrp', '0010_auto_20210220_0057'),
        ('others', '0002_auto_20210220_1752'),
        ('lessons', '0002_lesson_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='harrp.school', verbose_name='School'),
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='harrp.studentprofile', verbose_name='Created By')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentnote_notes', to='lessons.lesson', verbose_name='Lesson')),
                ('shared', models.ManyToManyField(related_name='Note', to='harrp.StudentProfile', verbose_name='Shared With')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentnote_notes', to='others.topic', verbose_name='Topic')),
            ],
            options={
                'verbose_name_plural': 'Student Notes',
            },
        ),
        migrations.CreateModel(
            name='AdminNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adminnote_notes', to='lessons.lesson', verbose_name='Lesson')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adminnote_notes', to='others.topic', verbose_name='Topic')),
            ],
            options={
                'verbose_name_plural': 'Admin Notes',
            },
        ),
    ]
