# Generated by Django 3.1.3 on 2021-04-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harrp', '0011_auto_20210428_1815'),
        ('others', '0003_auto_20210428_1815'),
        ('lessons', '0003_auto_20210221_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnote',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adminnote_notes', to='lessons.lesson', verbose_name='Lesson'),
        ),
        migrations.AlterField(
            model_name='adminnote',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adminnote_notes', to='others.topic', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='harrp.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='others.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='others.topic', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='harrp.studentprofile', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentnote_notes', to='lessons.lesson', verbose_name='Lesson'),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentnote_notes', to='others.topic', verbose_name='Topic'),
        ),
    ]
