# Generated by Django 3.1.3 on 2021-04-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20210428_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
    ]
