# Generated by Django 3.1.3 on 2021-05-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20210428_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentnote',
            old_name='creator',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='adminnote',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='studentnote',
            name='lesson',
        ),
    ]
