# Generated by Django 3.1.3 on 2021-05-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harrp', '0015_auto_20210503_2117'),
        ('lessons', '0006_auto_20210508_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='harrp.studentprofile', verbose_name='Created By'),
        ),
    ]
