# Generated by Django 3.1.3 on 2021-06-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_studentnote_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='class_name',
            field=models.CharField(blank=True, choices=[('JS 1', 'JS 1'), ('JS 2', 'JS 2'), ('JS 3', 'JS 3'), ('SS 1', 'SS 1'), ('SS 2', 'SS 2'), ('SS 3', 'SS 3')], max_length=50, null=True, verbose_name='Class'),
        ),
    ]
